<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class ItemSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'name' => 'Pulpen Pilot 0.7mm Hitam',
                'description' => 'Pulpen tinta hitam untuk dokumen resmi.',
                'stock' => 200,
                'price' => 6000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pulpen Pilot 0.7mm Biru',
                'description' => 'Pulpen tinta biru untuk catatan sidang.',
                'stock' => 150,
                'price' => 6000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kertas HVS A4 70gsm',
                'description' => 'Kertas untuk cetak dokumen pengadilan.',
                'stock' => 50,
                'price' => 55000.00,
                'supplier_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kertas HVS F4 70gsm',
                'description' => 'Kertas legal untuk dokumen resmi.',
                'stock' => 40,
                'price' => 60000.00,
                'supplier_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Map Snelhecter Plastik',
                'description' => 'Map untuk arsip dokumen perkara.',
                'stock' => 100,
                'price' => 3500.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Map Biola Karton',
                'description' => 'Map karton untuk penyimpanan berkas.',
                'stock' => 80,
                'price' => 4000.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tinta Printer Epson Hitam',
                'description' => 'Tinta untuk printer dokumen resmi.',
                'stock' => 20,
                'price' => 95000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tinta Printer HP Warna',
                'description' => 'Tinta warna untuk keperluan cetak khusus.',
                'stock' => 15,
                'price' => 120000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Catatan Sidang A5',
                'description' => 'Buku untuk mencatat jalannya sidang.',
                'stock' => 150,
                'price' => 15000.00,
                'supplier_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Buku Tulis Folio',
                'description' => 'Buku untuk catatan administrasi.',
                'stock' => 100,
                'price' => 10000.00,
                'supplier_id' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amplop Coklat A4',
                'description' => 'Amplop untuk surat resmi pengadilan.',
                'stock' => 200,
                'price' => 1500.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Amplop Putih Kecil',
                'description' => 'Amplop untuk surat internal.',
                'stock' => 300,
                'price' => 1000.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stapler Kenko',
                'description' => 'Alat untuk menjilid dokumen.',
                'stock' => 30,
                'price' => 25000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Isi Stapler No. 10',
                'description' => 'Isi ulang stapler untuk dokumen.',
                'stock' => 100,
                'price' => 8000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pembolong Kertas',
                'description' => 'Alat pelubang untuk arsip binder.',
                'stock' => 25,
                'price' => 20000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Binder Clip 25mm',
                'description' => 'Klip untuk mengikat dokumen.',
                'stock' => 200,
                'price' => 2000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Penghapus Staedtler',
                'description' => 'Penghapus untuk koreksi tulisan pensil.',
                'stock' => 150,
                'price' => 4000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pensil Faber-Castell 2B',
                'description' => 'Pensil untuk catatan sementara.',
                'stock' => 200,
                'price' => 3000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spidol Snowman Whiteboard',
                'description' => 'Spidol untuk papan tulis sidang.',
                'stock' => 50,
                'price' => 10000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Spidol Permanen Sharpie',
                'description' => 'Spidol untuk penandaan dokumen.',
                'stock' => 60,
                'price' => 12000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pita Printer Dot Matrix',
                'description' => 'Pita untuk printer dot matrix laporan.',
                'stock' => 20,
                'price' => 30000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ordner Bantex',
                'description' => 'Ordner untuk arsip dokumen besar.',
                'stock' => 30,
                'price' => 45000.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Box File Plastik',
                'description' => 'Kotak arsip untuk dokumen perkara.',
                'stock' => 25,
                'price' => 35000.00,
                'supplier_id' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kalkulator Casio 12 Digit',
                'description' => 'Kalkulator untuk administrasi keuangan.',
                'stock' => 15,
                'price' => 85000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Lem Kertas Glue Stick',
                'description' => 'Lem untuk dokumen atau catatan.',
                'stock' => 100,
                'price' => 7000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Selotip Bening 1 Inch',
                'description' => 'Selotip untuk keperluan pengemasan.',
                'stock' => 120,
                'price' => 5000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gunting Kertas 6 Inch',
                'description' => 'Gunting untuk keperluan kantor.',
                'stock' => 40,
                'price' => 15000.00,
                'supplier_id' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Post-it Note 3x3',
                'description' => 'Kertas catatan tempel untuk pengingat.',
                'stock' => 80,
                'price' => 10000.00,
                'supplier_id' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Stempel Sidang',
                'description' => 'Stempel resmi untuk dokumen sidang.',
                'stock' => 10,
                'price' => 50000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tinta Stempel Trodat',
                'description' => 'Tinta untuk stempel dokumen resmi.',
                'stock' => 20,
                'price' => 25000.00,
                'supplier_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        DB::table('items')->insert($items);
    }
}